version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: openmusic-redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: openmusic-rabbitmq
    ports:
      - "5672:5672"   # Port koneksi aplikasi
      - "15672:15672" # Port dashboard (bisa dibuka di browser: localhost:15672)
    restart: always